package views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author chars_mc
 */
public class AnalyzerView extends javax.swing.JFrame {

  public javax.swing.JButton getAnalyzeBtn() {
    return analyzeBtn;
  }

  public javax.swing.JButton getClearBtn() {
    return clearBtn;
  }

  public javax.swing.JButton getLoadFileBtn() {
    return loadFileBtn;
  }

  public javax.swing.JTextArea getResultOutput() {
    return resultOutput;
  }

  public javax.swing.JTextArea getTextInput() {
    return textInput;
  }

  /**
   * Creates new form Analyzer
   */
  public AnalyzerView() {
    setTitle("Lexical & Syntactic Analyzer");
    setVisible(true);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mainWindow = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    textInput = new javax.swing.JTextArea();
    jScrollPane1 = new javax.swing.JScrollPane();
    resultOutput = new javax.swing.JTextArea();
    loadFileBtn = new javax.swing.JButton();
    clearBtn = new javax.swing.JButton();
    analyzeBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(26, 28, 35));
    setLocation(new java.awt.Point(0, 0));
    setResizable(false);

    mainWindow.setBackground(new java.awt.Color(26, 28, 35));

    title.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    title.setForeground(new java.awt.Color(233, 86, 120));
    title.setText("LEXER & SINTACTIC ANALYZER");

    jScrollPane2.setBorder(null);

    textInput.setBackground(new java.awt.Color(22, 22, 28));
    textInput.setColumns(20);
    textInput.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
    textInput.setForeground(new java.awt.Color(250, 194, 154));
    textInput.setRows(5);
    jScrollPane2.setViewportView(textInput);

    jScrollPane1.setBorder(null);

    resultOutput.setBackground(new java.awt.Color(35, 37, 48));
    resultOutput.setColumns(20);
    resultOutput.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
    resultOutput.setForeground(new java.awt.Color(249, 203, 190));
    resultOutput.setRows(5);
    resultOutput.setBorder(null);
    resultOutput.setEnabled(false);
    resultOutput.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        resultOutputFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        resultOutputFocusLost(evt);
      }
    });
    jScrollPane1.setViewportView(resultOutput);

    loadFileBtn.setBackground(new java.awt.Color(39, 215, 150));
    loadFileBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    loadFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/load.png"))); // NOI18N
    loadFileBtn.setText("LOAD FILE");
    loadFileBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    loadFileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    loadFileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loadFileBtnActionPerformed(evt);
      }
    });

    clearBtn.setBackground(new java.awt.Color(244, 62, 92));
    clearBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
    clearBtn.setText("CLEAR");
    clearBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        clearBtnMouseClicked(evt);
      }
    });

    analyzeBtn.setBackground(new java.awt.Color(39, 215, 150));
    analyzeBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    analyzeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analyse.png"))); // NOI18N
    analyzeBtn.setText("ANALYZE");
    analyzeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    analyzeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    analyzeBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        analyzeBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout mainWindowLayout = new javax.swing.GroupLayout(mainWindow);
    mainWindow.setLayout(mainWindowLayout);
    mainWindowLayout.setHorizontalGroup(
      mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainWindowLayout.createSequentialGroup()
        .addGroup(mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(mainWindowLayout.createSequentialGroup()
            .addGap(294, 294, 294)
            .addComponent(title)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(mainWindowLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(loadFileBtn)
            .addGap(180, 180, 180)
            .addComponent(analyzeBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clearBtn))
          .addGroup(mainWindowLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    mainWindowLayout.setVerticalGroup(
      mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainWindowLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(title)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(loadFileBtn)
          .addComponent(analyzeBtn)
          .addComponent(clearBtn))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(443, 443, 443))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(mainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(mainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    mainWindow.getAccessibleContext().setAccessibleName("main_window");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void loadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileBtnActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_loadFileBtnActionPerformed

  private void clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseClicked
    // TODO add your handling code here:
    if (getResultOutput().getText() != "") {
      getResultOutput().setText("");
      getClearBtn().setEnabled(false);
    }
  }//GEN-LAST:event_clearBtnMouseClicked

  private void resultOutputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resultOutputFocusGained
    // TODO add your handling code here:
    if (getResultOutput().getText() != "")
      getClearBtn().setEnabled(true);
  }//GEN-LAST:event_resultOutputFocusGained

  private void resultOutputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resultOutputFocusLost
    // TODO add your handling code here:
    if (getResultOutput().getText() != "")
      getClearBtn().setEnabled(true);
  }//GEN-LAST:event_resultOutputFocusLost

  private void analyzeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeBtnActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_analyzeBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AnalyzerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AnalyzerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AnalyzerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AnalyzerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AnalyzerView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton analyzeBtn;
  private javax.swing.JButton clearBtn;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton loadFileBtn;
  private javax.swing.JPanel mainWindow;
  private javax.swing.JTextArea resultOutput;
  private javax.swing.JTextArea textInput;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
